version: '3'
services:
  app:
    build: ./app
    expose:
      - "8080"
    env_file:
      - ./app.env
    volumes:
      - ./app/prisma:/home/node/app/prisma
  #  depends_on:
  #    - db
  #db:
  #  image: "postgres:alpine"
  #  restart: always
  #  volumes:
  #    - ./postgres-data:/var/lib/postgresql/data
  #  env_file:
  #    - ./db.env
  #  networks:
  #      internal:
  nginx:
    build: ./shibboleth
    command: "/bin/sh -c '/usr/bin/supervisord; /etc/init.d/shibd restart; while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/shib/sp-cert.pem:/etc/shibboleth/sp-cert.pem
      - ./data/shib/sp-key.pem:/etc/shibboleth/sp-key.pem
    depends_on:
      - app
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot