version: '3'
services:
  app:
    build: ./app
    expose:
      - "8080"
    volumes:
      - ./data/app/discord.csv:/home/node/app/discord.csv
    environment:
      DATABASE_URL: "postgresql://dbuser:dbpassword@db:5432/postgresdb"
      REDIS_URL: "redis://cache:6379"
      DISCORD_CLIENT_ID: ""
      DISCORD_CLIENT_SECRET: ""
      DISCORD_BOT_TOKEN: ""
      APP_HOSTNAME: "https://shib.sigpwny.com"
      JWT_SECRET: "changeme123"=
      ADMIN_USER_IDS: "181927679195480064"
    depends_on:
      - cache
      - db
    networks:
        internal:
  cache:
    image: "redis:alpine"
    restart: always
    networks:
        internal:
  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    networks:
        internal:
  nginx:
    build: ./shibboleth
    command: "/bin/sh -c '/usr/bin/supervisord; /etc/init.d/shibd restart; while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/shib/sp-cert.pem:/etc/shibboleth/sp-cert.pem
      - ./data/shib/sp-key.pem:/etc/shibboleth/sp-key.pem
    depends_on:
      - app
    networks:
      default:
      internal:
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      internal:
networks:
  default:
  internal:
      internal: true